name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Initialize database
        run: poetry run python3 src/build.py
      - name: Run tests
        run: poetry run pytest src
      - name: Robot tests
        run: poetry run robot src
        continue-on-error: true
      - name: Test branch coverage
        run: poetry run coverage run --branch -m pytest
      - name: Make XML report from coverage run
        run: poetry run coverage xml
      - name: Pylint check
        run: poetry run pylint src
        continue-on-error: true
      - name: Inform Codecov about new coverage report
        run: bash <(curl -s https://codecov.io/bash)
